### ISSUE TITLE
CAN ANYONE SEND ME SOME GOERLI 0xE834bf72F2df2F4E8e6fd2b9Cfeb0C3EcBdB8A4e

### ISSUE THREAD

**Issue by Ash1shh** [mateuszsokola/eth-faucet#24]
0xE834bf72F2df2F4E8e6fd2b9Cfeb0C3EcBdB8A4e
0xE834bf72F2df2F4E8e6fd2b9Cfeb0C3EcBdB8A4e
0xE834bf72F2df2F4E8e6fd2b9Cfeb0C3EcBdB8A4e
0xE834bf72F2df2F4E8e6fd2b9Cfeb0C3EcBdB8A4e
0xE834bf72F2df2F4E8e6fd2b9Cfeb0C3EcBdB8A4e
0xE834bf72F2df2F4E8e6fd2b9Cfeb0C3EcBdB8A4e

**Comment by mateuszsokola** [comment]
https://goerli.etherscan.io/tx/0xeb8acf96231107a59c04a672b13a9b0b57f17c9cec1b3ba94289964e060e7939 - 1 Ether
